service: cadastro-pacientes

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dynamodb-local


custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true  
    seed:
      domain:
        sources:
          - table: PACIENTES
            sources: [./offline/pacientes-seed.json]

#informar o provider (aws , google cloud, azure, etc.)
provider:
  name: aws
  runtime: nodejs12.x

  #informa o ambiente e a região
  stage: dev
  region: us-east-1

  #configuração para carregar diferentes dados dependendo do ambiente
  environment:
    PACIENTES_TABLE: 'PACIENTES-${opt:stage, self:provider.stage}'

#aqui é informado as permissões que os serão utilizadas pelas functions, onde é informada o tipo do produto é a operação
#o Resoruce é o arn do recurso que será utilizado as permissões especificads
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamo:UpdateItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PACIENTES_TABLE}'


#informa as functions onde e especificado o nome da function e o header de execução da function
#os events são os gatilhos que vão ativar essas functions, nos exemplos abaixo, os gatilhos são API Rest utilizando o API Gateway da AWS
functions:
  hello:
    handler: handler.hello

  listarPacientes:
    handler: handler.listarPacientes
    
    events:
      - http:  
          path: pacientes
          method: get

  buscarPaciente:
    handler: handler.buscarPaciente
    
    events:
      - http:  
          path: pacientes/{pacienteId}
          method: get
          request:
            parameters:
              paths:
                pacienteId: false

  cadastrarPaciente:
    handler: handler.cadastrarPaciente

    events:
      - http:  
          path: pacientes
          method: post
          
  atualizarPaciente:
    handler: handler.atualizarPaciente
    
    events:
      - http:  
          path: pacientes/{pacienteId}
          method: put
          request:
            parameters:
              paths:
                pacienteId: false

  deletarPaciente:
    handler: handler.deletarPaciente
    
    events:
      - http:  
          path: pacientes/{pacienteId}
          method: Delete
        
  


  


#é informado os recursos que serão utilizados pelas functions
#neste exemplo é informado que será utilizado uma recurso com nome de PacienteTable que tem o tipo AWS::DynamoDB::Table
#que é um banco DynamoDB da AWS, e é informado os recursos para a criação da tabela no banco
resources:
  Resources:
    PacientesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PACIENTES_TABLE}
        AttributeDefinitions:
          - AttributeName: paciente_id
            AttributeType: S
        KeySchema:
          - AttributeName: paciente_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
       
