service: cadastro-pacientes

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

stage: dev
region: us-east-1

functions:
  hello:
    handler: handler.hello

  listarPacientes:
    handler: handler.listarPacientes
    
    events:
      - http:  
          path: pacientes
          method: get

  buscarPaciente:
    handler: handler.buscarPaciente
    
    events:
      - http:  
          path: pacientes/{pacienteId}
          method: get
          request:
            parameters:
              paths:
                pacienteId: false



       
